// DO NOT EDIT THIS FILE WITHIN THE kolo-django FOLDER
// COPY THE confidential FOLDER INTO THE PARENT FOLDER
// THEN REMOVE THIS MESSAGE
window.kolo_settings = {
    'couchdb': 'INSERT_URL_TO_COUCHDB',
    'user': {
        'name': 'YOURNAME',
        'password': '',
    },
    'csv': {
        'people': '../../confidential/people.csv',
    }
}
