// DO NOT EDIT THIS FILE WITHIN THE kolo-django FOLDER
// COPY THE confidential FOLDER INTO THE PARENT FOLDER
// THEN REMOVE THIS MESSAGE
window.kolo_settings = {
    //'couchdb': 'http://localhost:32768/kolo',
    'couchdb': 'kolo',
    'csv': {
        'people': '../../confidential/people.csv',
    }
}
